# -*- coding:utf-8 -*-
# @author  : Shuai Pang
# @time    : 2026-04

"""
Voronoi-based spatial regularity analysis of urban centers (Figure 4).

Computation:
  - Generates empirical Voronoi partitions of urban centers within city boundaries.
  - Runs Monte Carlo simulations under two null models:
    * CSR (Complete Spatial Randomness): uniform random points within city polygons.
    * SSI (Sequential Spatial Inhibition): random points with minimum inter-point
      distance derived from the minimum contour area threshold (4 km2).
  - Outputs: empirical Voronoi shapefile and cached null model statistics (.npz).

Figure 4:
    (a) Voronoi partition of Los Angeles with center points.
    (b) Violin plot of Voronoi cell areas across countries (mono- vs polycentric).
    (c) Error bar plot of Voronoi cell areas for selected cities.
    (d) Schematic of null models (CSR and SSI) — not generated by this code.
    (e) KDE of CV and mean NND from CSR/SSI null models vs empirical.
"""

import os

import geopandas as gpd
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
import matplotlib.transforms as transforms
import numpy as np
import pandas as pd
from pyproj import Geod, Transformer
from scipy.stats import gaussian_kde
from shapely import voronoi_polygons
from shapely.geometry import LineString, MultiPoint, MultiPolygon, Point
from shapely.ops import split, unary_union
from sklearn.neighbors import BallTree
from tqdm import tqdm

import Parameters.consts as const
import Parameters.plot_utils as utils

# ── Constants ─────────────────────────────────────────────────────────────────

CLUSTERS_PATH = const.FILE_PATH + r'2020\Input\GHSL_UCDB_MTUC_2020_GLOBE_R2024_WGS84.shp'
CENTERS_PATH = const.FILE_PATH + r'2020\Center\center_a4.shp'
VORONOI_PATH = const.FILE_PATH + r'2020\Statistics\Voronoi\voronoi_emp.shp'
NULL_MODEL_PATH = const.FILE_PATH + r'2020\Statistics\Voronoi\null_model_cache.npz'
OUTPUT_PATH = r'D:\Research\Graph\GHSL\panel\spatial_pattern.png'

MIN_CONTOUR_AREA = 4.0  # km2
INHIBITION_RADIUS = 2 * np.sqrt(MIN_CONTOUR_AREA / np.pi) * 1000  # meters
N_SIMULATIONS = 99

LA_ID = 2007
COUNTRIES = [0, 91, 93, 142, 1]
COUNTRY_NAMES = {0: 'China', 91: 'Germany', 93: 'UK', 142: 'US', 1: 'Japan'}

CITY_DICT = {
    0:   [11345, 10933],
    91:  [693, 5483],
    93:  [3340, 5816],
    142: [8099, 2007],
    1:   [5929, 4399],
}
CITY_NAMES = {
    2007: 'Los Angeles', 8099: 'New York',
    10933: 'Guangzhou', 11345: 'Shanghai',
    693: 'Essen', 5483: 'Berlin',
    5816: 'London', 3340: 'Manchester',
    5929: 'Tokyo', 4399: 'Osaka',
}


# ── Point generation ──────────────────────────────────────────────────────────

def _random_csr(polys, rng):
    """Generate CSR (uniform random) points within each city polygon."""
    gdf = polys.copy().to_crs(3857)
    all_points, all_ids = [], []
    for _, row in gdf.iterrows():
        poly = row.geometry
        n = int(row['Center_Num'])
        if n <= 0:
            continue
        minx, miny, maxx, maxy = poly.bounds
        pts = []
        while len(pts) < n:
            x, y = rng.uniform(minx, maxx), rng.uniform(miny, maxy)
            if poly.contains(Point(x, y)):
                pts.append(Point(x, y))
        all_points.extend(pts)
        all_ids.extend([row['ID_UC_G0']] * n)
    return gpd.GeoDataFrame({'ID_UC_G0': all_ids}, geometry=all_points, crs=gdf.crs).to_crs(4326)


def _random_ssi(polys, rng, max_attempts=10000):
    """Generate SSI points with minimum geodesic distance constraint."""
    geod = Geod(ellps='WGS84')
    transformer = Transformer.from_crs(3857, 4326, always_xy=True)
    gdf = polys.copy().to_crs(3857)
    all_points, all_ids = [], []

    for _, row in gdf.iterrows():
        poly = row.geometry
        n = int(row['Center_Num'])
        city_id = row['ID_UC_G0']
        if n <= 0:
            continue

        pts, pts_lonlat = [], []
        minx, miny, maxx, maxy = poly.bounds
        attempts = 0
        while len(pts) < n and attempts < max_attempts * n:
            x, y = rng.uniform(minx, maxx), rng.uniform(miny, maxy)
            attempts += 1
            if not poly.contains(Point(x, y)):
                continue
            lon, lat = transformer.transform(x, y)
            if pts_lonlat:
                lons_acc, lats_acc = zip(*pts_lonlat)
                _, _, dists = geod.inv(
                    [lon] * len(pts_lonlat), [lat] * len(pts_lonlat),
                    list(lons_acc), list(lats_acc))
                if min(dists) < INHIBITION_RADIUS:
                    continue
            pts.append(Point(x, y))
            pts_lonlat.append((lon, lat))

        if len(pts) < n:
            print(f"Warning: city {city_id} only placed {len(pts)}/{n} points")
        all_points.extend(pts)
        all_ids.extend([city_id] * len(pts))

    return gpd.GeoDataFrame({'ID_UC_G0': all_ids}, geometry=all_points, crs=gdf.crs).to_crs(4326)


# ── Voronoi computation ───────────────────────────────────────────────────────

def _points_to_voronoi(coords, clip_poly):
    """Compute Voronoi polygons for points within a clipping polygon."""
    n = len(coords)
    if n == 1:
        return [clip_poly]

    if n == 2:
        mid = coords.mean(axis=0)
        vec = coords[1] - coords[0]
        perp = np.array([-vec[1], vec[0]])
        line = LineString([mid - perp * 1e5, mid + perp * 1e5])
        split_polys = [p for p in split(clip_poly, line).geoms if not p.is_empty]
        left, right = [], []
        for p in split_polys:
            c = np.array([p.centroid.x, p.centroid.y])
            cross = perp[0] * (c[1] - mid[1]) - perp[1] * (c[0] - mid[0])
            (left if cross > 0 else right).append(p)
        return [unary_union(left), unary_union(right)]

    points = [Point(c) for c in coords]
    mp = MultiPoint(points)
    try:
        vor = voronoi_polygons(mp, extend_to=clip_poly)
    except Exception:
        rng_jitter = np.random.default_rng(seed=hash(coords.tobytes()) & 0xFFFFFFFF)
        jittered = coords + rng_jitter.uniform(-0.01, 0.01, coords.shape)
        mp = MultiPoint([Point(c) for c in jittered])
        try:
            vor = voronoi_polygons(mp, extend_to=clip_poly)
        except Exception:
            try:
                vor = voronoi_polygons(mp)
            except Exception:
                return None

    clip_valid = clip_poly if clip_poly.is_valid else clip_poly.buffer(0)
    result = [None] * n
    for cell in vor.geoms:
        clipped = cell.intersection(clip_valid)
        if clipped.is_empty:
            continue
        for i, pt in enumerate(points):
            if result[i] is None and cell.contains(pt):
                result[i] = clipped
                break

    for i in range(n):
        if result[i] is not None:
            continue
        pt = points[i]
        best_dist, best_cell = float('inf'), None
        for cell in vor.geoms:
            d = cell.boundary.distance(pt)
            if d < best_dist:
                best_dist, best_cell = d, cell
        if best_cell is not None:
            result[i] = best_cell.intersection(clip_valid)

    return None if any(r is None for r in result) else result


def voronoi_partition(pts, polys):
    """Generate Voronoi partitions of centers within each city polygon."""
    pts = pts.to_crs(3857)
    polys = polys.to_crs(3857)
    results = []

    for _, poly_row in tqdm(polys.iterrows(), total=len(polys), leave=False):
        poly_geom = poly_row.geometry
        idx = poly_row['ID_UC_G0']
        pts_in = pts[pts['ID_UC_G0'] == idx]
        country = poly_row['Country']

        if len(pts_in) == 0:
            continue
        coords = np.vstack(pts_in.geometry.apply(lambda p: (p.x, p.y)).values)
        vor_polys = _points_to_voronoi(coords, poly_geom.buffer(0))

        if vor_polys is None:
            print(f"\nSkipping ID_UC_G0 {idx} due to unresolvable topology")
            continue

        results.append(gpd.GeoDataFrame({
            'ID_UC_G0': [idx] * len(vor_polys),
            'Country': [country] * len(vor_polys),
            'CenterIdx': pts_in.index.tolist(),
        }, geometry=vor_polys, crs=polys.crs))

    merged = gpd.GeoDataFrame(pd.concat(results, ignore_index=True), crs=polys.crs)
    merged.geometry = merged.geometry.apply(lambda g: g.buffer(0) if g is not None else g)

    merged_4326 = merged.to_crs(4326)
    geod = Geod(ellps='WGS84')
    merged['Area'] = merged_4326.geometry.apply(
        lambda geom: abs(geod.geometry_area_perimeter(geom)[0]) / 1e6)

    return merged


# ── Spatial metrics ───────────────────────────────────────────────────────────

def _mark_interior(voronoi_gdf, polys):
    """Mark Voronoi cells as interior (True) if they don't touch the city boundary."""
    voronoi_proj = voronoi_gdf.to_crs(3857)
    polys_proj = polys.to_crs(3857)
    boundary_map = dict(zip(polys_proj['ID_UC_G0'], polys_proj.geometry.boundary))

    is_interior = pd.Series(True, index=voronoi_proj.index)
    for idx, row in voronoi_proj.iterrows():
        boundary = boundary_map.get(row['ID_UC_G0'])
        if boundary is not None and row.geometry is not None:
            try:
                is_interior[idx] = not row.geometry.intersects(boundary)
            except Exception:
                is_interior[idx] = False
    return is_interior


def _pool_nnd(pts_gdf, voronoi_gdf, valid_ids, interior_mask):
    """Compute pooled nearest-neighbor distances for interior centers."""
    geod = Geod(ellps='WGS84')
    if pts_gdf.crs is not None and pts_gdf.crs.to_string() != "EPSG:4326":
        pts_gdf = pts_gdf.to_crs(4326)
    lons = pts_gdf.geometry.x.values
    lats = pts_gdf.geometry.y.values
    coords_rad = np.column_stack([np.radians(lats), np.radians(lons)])
    groups = pts_gdf['ID_UC_G0'].values

    vor_interior = interior_mask.values if hasattr(interior_mask, 'values') else np.array(interior_mask)
    city_interior = {}
    for g_id in valid_ids:
        city_interior[g_id] = vor_interior[voronoi_gdf['ID_UC_G0'].values == g_id]

    all_nnd = []
    for g_id in np.unique(groups):
        if g_id not in valid_ids:
            continue
        mask = groups == g_id
        n_pts = mask.sum()
        if n_pts < 2:
            continue
        is_int = city_interior.get(g_id)
        if is_int is None or len(is_int) != n_pts:
            continue
        g_coords = coords_rad[mask]
        g_lons, g_lats = lons[mask], lats[mask]
        tree = BallTree(g_coords, metric='haversine')
        _, indices = tree.query(g_coords, k=2)
        nb = indices[:, 1]
        _, _, dists = geod.inv(g_lons, g_lats, g_lons[nb], g_lats[nb])
        for j in range(n_pts):
            if is_int[j]:
                all_nnd.append(dists[j])
    return np.array(all_nnd)


# ── Null model simulation ─────────────────────────────────────────────────────

def run_null_model(pts_emp, polys, voronoi_emp, n_sim=N_SIMULATIONS):
    """Run CSR and SSI null model simulations, cache results to .npz."""
    emp_interior = _mark_interior(voronoi_emp, polys)
    valid_ids = set(polys['ID_UC_G0'].values)

    emp_sub = voronoi_emp[emp_interior]
    emp_areas = emp_sub['Area'].values
    cv_emp = emp_areas.std() / emp_areas.mean()
    nnd_emp = _pool_nnd(pts_emp, voronoi_emp, valid_ids, emp_interior).mean()
    print(f"Empirical: CV={cv_emp:.4f}, Mean NND={nnd_emp:.0f}m")

    if os.path.exists(NULL_MODEL_PATH):
        print(f"Cache exists: {NULL_MODEL_PATH}")
        return

    rng = np.random.default_rng(42)
    cv_csr, nnd_csr = np.empty(n_sim), np.empty(n_sim)
    cv_ssi, nnd_ssi = np.empty(n_sim), np.empty(n_sim)

    for i in tqdm(range(n_sim), desc="Null model simulations"):
        pts_csr = _random_csr(polys, rng)
        vor_csr = voronoi_partition(pts_csr, polys)
        int_csr = _mark_interior(vor_csr, polys)
        areas = vor_csr[int_csr]['Area'].values
        cv_csr[i] = areas.std() / areas.mean() if len(areas) > 1 else np.nan
        nnd_arr = _pool_nnd(pts_csr, vor_csr, valid_ids, int_csr)
        nnd_csr[i] = nnd_arr.mean() if len(nnd_arr) > 0 else np.nan

        pts_ssi = _random_ssi(polys, rng)
        vor_ssi = voronoi_partition(pts_ssi, polys)
        int_ssi = _mark_interior(vor_ssi, polys)
        areas = vor_ssi[int_ssi]['Area'].values
        cv_ssi[i] = areas.std() / areas.mean() if len(areas) > 1 else np.nan
        nnd_arr = _pool_nnd(pts_ssi, vor_ssi, valid_ids, int_ssi)
        nnd_ssi[i] = nnd_arr.mean() if len(nnd_arr) > 0 else np.nan

    np.savez(NULL_MODEL_PATH,
             cv_poisson=cv_csr, nnd_poisson=nnd_csr,
             cv_ssi=cv_ssi, nnd_ssi=nnd_ssi,
             cv_emp=cv_emp, nnd_emp=nnd_emp)
    print(f"Saved cache to {NULL_MODEL_PATH}")


# ── Panel plot functions ──────────────────────────────────────────────────────

def _plot_la_voronoi(ax):
    """Fig. 4a: Voronoi partition of Los Angeles with center points."""
    boundary = gpd.read_file(CLUSTERS_PATH, where=f"ID_UC_G0 = {LA_ID}").to_crs('EPSG:3857')
    centers = gpd.read_file(CENTERS_PATH, where=f"ID_UC_G0 = {LA_ID}").to_crs('EPSG:3857')
    voronoi = gpd.read_file(VORONOI_PATH, where=f"ID_UC_G0 = {LA_ID}").to_crs('EPSG:3857')

    highlight_ids = [335, 360, 361]
    voronoi_hi = voronoi[voronoi['CenterIdx'].isin(highlight_ids)]
    voronoi_lo = voronoi[~voronoi['CenterIdx'].isin(highlight_ids)]

    voronoi_lo.plot(ax=ax, facecolor='none', edgecolor='#a6a6a6', linewidth=0.3)
    voronoi_hi.plot(ax=ax, facecolor='#e1e1e1', edgecolor='#a6a6a6', linewidth=0.3)
    boundary.plot(ax=ax, facecolor='none', edgecolor='#a6a6a6', linewidth=0.5)

    main = centers[centers['Main'] == 1]
    sub = centers[centers['Main'] != 1]
    sub.plot(ax=ax, color='#cf82d9', markersize=10, edgecolor='black', linewidth=0.2, zorder=5)
    main.plot(ax=ax, color='#cf82d9', marker='*', markersize=50, edgecolor='black', linewidth=0.2, zorder=6)

    xmin, ymin, xmax, ymax = voronoi.total_bounds
    ax.set_xlim(xmin, xmax)
    ax.set_ylim(ymin, None)
    ax.set_aspect('equal')
    ax.axis('off')


def _plot_country_violin(ax, gdf):
    """Fig. 4b: violin plot of Voronoi cell areas across countries."""
    group_sizes = gdf.groupby(['Country', 'ID_UC_G0'])['ID_UC_G0'].transform('size')
    gdf['Type'] = group_sizes.apply(lambda x: 'Mono' if x == 1 else 'Poly')

    colors = {'Mono': '#1DA0CC', 'Poly': '#C061CC'}

    for i, country in enumerate(COUNTRIES):
        for j, t in enumerate(['Mono', 'Poly']):
            vals = gdf[(gdf['Country'] == country) & (gdf['Type'] == t)]['Area'].values
            kde = gaussian_kde(vals, bw_method=0.4)
            y = np.linspace(0, 200, 200)
            density = kde(y) * 12.5

            if t == 'Mono':
                pos = i - 0.125
                ax.fill_betweenx(y, pos - density, pos, facecolor=colors[t], alpha=0.5, linewidth=0)
            else:
                pos = i + 0.125
                ax.fill_betweenx(y, pos, pos + density, facecolor=colors[t], alpha=0.6, linewidth=0)

            box_pos = i + (j - 0.5) * 0.15
            mean_val = np.mean(vals)
            std = np.std(vals)
            ax.plot([box_pos, box_pos], [mean_val - std, mean_val + std],
                    color='black', linewidth=0.5, solid_capstyle='round', zorder=2)
            ax.scatter(box_pos, mean_val, marker='s', s=10,
                       color=colors[t], edgecolor='none', lw=0, zorder=3)

    ax.set_xticks(ticks=np.arange(len(COUNTRIES)),
                  labels=[COUNTRY_NAMES[c] for c in COUNTRIES])
    ax.set_yticks([0, 50, 100, 150])
    ax.set_xlabel(None)
    ax.set_ylabel("Area of the center's voronoi polygon (km2)")
    ax.set_ylim(0, 150)
    utils.FormatAxis(ax, positions=[])
    ax.spines['bottom'].set_position(('outward', 8))
    ax.tick_params(axis='x', which='major', pad=3)


def _plot_city_errorbar(ax, gdf):
    """Fig. 4c: error bar plot of Voronoi cell areas for selected cities."""
    gap = 0.4
    color = '#AF58BA'
    means = []

    for i, country in enumerate(CITY_DICT):
        for j, city in enumerate(CITY_DICT[country]):
            y_pos = i + j * gap
            values = gdf[(gdf['Country'] == country) & (gdf['ID_UC_G0'] == city)]['Area'].values
            mean_val = np.mean(values)
            means.append(mean_val)
            std = np.std(values)

            ax.scatter(mean_val, y_pos, marker='s', s=15, color=color, edgecolor='none', lw=0, zorder=10)
            ax.plot([mean_val - std, mean_val + std], [y_pos, y_pos],
                    color='black', lw=0.8, solid_capstyle='round')
            ax.text(-10, y_pos, CITY_NAMES[city], va='center', ha='right', color='black')

    for i, country in enumerate(CITY_DICT):
        ax.text(-70, i + gap / 2, COUNTRY_NAMES[country], va='center', ha='center', color='black')
    ax.axvline(np.mean(means), color=color, lw=0.8, linestyle=(-3, (6, 6)), zorder=1)

    ax.set_xlim(-60, 100)
    ax.set_ylim(-0.2, 4.8)
    ax.set_xticks([0, 25, 50, 75, 100])
    ax.set_yticks([])
    ax.set_xlabel("Area of the center's voronoi polygon (km2)")
    ax.set_ylabel(None)
    utils.FormatAxis(ax, positions=[])


def _plot_kde_panel(ax, data_csr, data_ssi, emp_val, xlabel):
    """Single KDE sub-panel comparing CSR and SSI null models against empirical value."""
    dp = data_csr[~np.isnan(data_csr)]
    ds = data_ssi[~np.isnan(data_ssi)]

    kde_csr = gaussian_kde(dp)
    kde_ssi = gaussian_kde(ds)

    all_vals = np.concatenate([dp, ds, [emp_val]])
    pad = (all_vals.max() - all_vals.min()) * 0.15
    x_grid = np.linspace(all_vals.min() - pad, all_vals.max() + pad, 300)

    y_csr = kde_csr(x_grid)
    y_ssi = kde_ssi(x_grid)

    ci_csr = np.percentile(dp, [2.5, 97.5])
    ax.plot(x_grid, y_csr, color='#969696', lw=0.8, label='Poisson')
    ax.fill_between(x_grid, y_csr, where=(x_grid >= ci_csr[0]) & (x_grid <= ci_csr[1]),
                    color='#969696', alpha=0.3)

    ci_ssi = np.percentile(ds, [2.5, 97.5])
    ax.plot(x_grid, y_ssi, color='#1DA0CC', lw=0.8, label='SSI')
    ax.fill_between(x_grid, y_ssi, where=(x_grid >= ci_ssi[0]) & (x_grid <= ci_ssi[1]),
                    color='#1DA0CC', alpha=0.3)

    trans = transforms.blended_transform_factory(ax.transData, ax.transAxes)
    ax.plot(emp_val, 0.03, marker='s', color='#AF58BA', markersize=4, zorder=5,
            clip_on=False, label='Empirical', transform=trans)

    ax.set_xlabel(xlabel)
    ax.set_ylabel('Kernel density estimation', labelpad=utils.LABEL_PAD - 1)
    utils.FormatAxis(ax)


def _plot_null_model_kde(placeholder_ax):
    """Fig. 4e: KDE of CV and mean NND from CSR/SSI null models vs empirical."""
    data = np.load(NULL_MODEL_PATH)
    cv_csr = data['cv_poisson']
    cv_ssi = data['cv_ssi']
    cv_emp = float(data['cv_emp'])

    nnd_csr = data['nnd_poisson'] / 1000
    nnd_ssi = data['nnd_ssi'] / 1000
    nnd_emp = float(data['nnd_emp']) / 1000

    fig = placeholder_ax.get_figure()
    ss = placeholder_ax.get_subplotspec()
    sub_gs = gridspec.GridSpecFromSubplotSpec(2, 1, subplot_spec=ss, hspace=0.25)
    ax_d = fig.add_subplot(sub_gs[0, 0])
    ax_e = fig.add_subplot(sub_gs[1, 0])
    placeholder_ax.axis('off')

    _plot_kde_panel(ax_d, cv_csr, cv_ssi, cv_emp, 'CV of Voronoi cell areas')
    ax_d.set_xlim(0.3, 0.7)
    ax_d.set_ylim(0, 20)
    ax_d.set_xticks([0.3, 0.4, 0.5, 0.6, 0.7])
    ax_d.set_yticks([0, 10, 20])

    _plot_kde_panel(ax_e, nnd_csr, nnd_ssi, nnd_emp, 'Mean NND (km)')
    ax_e.set_xlim(2, 5)
    ax_e.set_ylim(0, 10)
    ax_e.set_xticks([2, 3, 4, 5])
    ax_e.set_yticks([0, 5, 10])


# ── Figure assembly ───────────────────────────────────────────────────────────

def figure4():
    """Compose and save Figure 4: spatial distribution of centers within cities."""
    voronoi_gdf = gpd.read_file(VORONOI_PATH)

    fig = plt.figure(figsize=(18 / 2.54, 15 / 2.54), dpi=600)
    gs_top = gridspec.GridSpec(1, 2, figure=fig, left=0.05, right=0.98, top=0.96, bottom=0.50,
                               width_ratios=[24, 12], wspace=0.1)
    gs_bot = gridspec.GridSpec(1, 3, figure=fig, left=0.08, right=0.98, top=0.48, bottom=0.08,
                               width_ratios=[11, 11, 12], wspace=0.25)

    ax_a = fig.add_subplot(gs_top[0, 0])
    ax_placeholder = fig.add_subplot(gs_top[0, 1])
    ax_b = fig.add_subplot(gs_bot[0, 0])
    ax_c = fig.add_subplot(gs_bot[0, 1])
    ax_de = fig.add_subplot(gs_bot[0, 2])

    _plot_la_voronoi(ax_a)
    ax_placeholder.axis('off')

    _plot_country_violin(ax_b, voronoi_gdf)
    _plot_city_errorbar(ax_c, voronoi_gdf)
    _plot_null_model_kde(ax_de)

    print(f"Saving to {OUTPUT_PATH}...")
    fig.savefig(OUTPUT_PATH, dpi=600, facecolor='white')
    plt.close(fig)
    print("Done.")


def generate_voronoi():
    """Generate empirical Voronoi partitions and run null model simulations."""
    polys = gpd.read_file(CLUSTERS_PATH)
    pts_emp = gpd.read_file(CENTERS_PATH)

    center_counts = pts_emp.groupby('ID_UC_G0').size().reset_index(name='Center_Num')
    polys = polys.merge(center_counts, on='ID_UC_G0', how='left')
    polys['Center_Num'] = polys['Center_Num'].fillna(0).astype(int)
    polys = polys[polys['Center_Num'] > 0].copy()

    print("Generating empirical Voronoi partitions...")
    voronoi_emp = voronoi_partition(pts_emp, polys)

    os.makedirs(os.path.dirname(VORONOI_PATH), exist_ok=True)
    voronoi_shp = voronoi_emp.copy()
    voronoi_shp.geometry = voronoi_shp.geometry.apply(
        lambda g: g if isinstance(g, MultiPolygon) else MultiPolygon([g]))
    voronoi_shp.to_file(VORONOI_PATH)
    print(f"Voronoi saved to {VORONOI_PATH}")

    print("Running null model simulations...")
    run_null_model(pts_emp, polys, voronoi_emp)
    print("Done.")


if __name__ == '__main__':
    figure4()
